title: [Jorge-Humberto Urrea-Quintero]

logo: [/images/20190514_175020_Small.jpg]

description: [Discovering the complexity of the world through the lenses of mathematics.]

theme: jekyll-theme-minimal
